### ISSUE TITLE
Miner's Lamp Helmet Price Display Wrong

### ISSUE THREAD

**Issue by law4x** [Octr/ValueTooltip#1]
Miner's Lamp Helmet Price Display Wrong
The price value display is related to the durability value of the item
![81EXD76V2X S5K7Q~L(1L8](https://user-images.githubusercontent.com/11098142/180023242-305ef114-8a81-4b4d-bfb4-f095bf223629.png)

**Comment by Octr** [comment]
Thanks your feedback!
Resolved in patch 1.0.0.1
